spring.application.name=Day23UserManagementApplication

#management.endpoints.web.exposure.include=health,metrics,beans,info,mappings
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

#spring.security.user.name=admin
#spring.security.user.password=admin123

spring.profiles.active=dev