spring.application.name=StudentSpringProject
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/springAngulardb
spring.datasource.username=root
spring.datasource.password=Cfg@1234